name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Enables manual trigger via GitHub UI

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --no-progress --no-interaction --prefer-dist
      - run: vendor/bin/phpunit --debug
        env:
          XDEBUG_MODE: coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --no-progress --no-interaction --prefer-dist
      - run: php vendor/bin/phpstan analyze
